name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: pytest tests

    - name: Set up JMeter
      run: sudo apt-get install jmeter -y

    - name: Run JMeter tests
      run: jmeter -n -t path/to/your_test_plan.jmx -l results.jtl
